### ISSUE TITLE
0.4.5 zip release: Incorrect version displayed

### ISSUE THREAD

**Issue by globalcitizen** [kevancress/MeasureIt-ARCH#103]
After installing from -0.4.5 zipfile from the releases page...

<img width="491" alt="Screen Shot 2020-07-22 at 10 54 58" src="https://user-images.githubusercontent.com/505366/88121680-d8113600-cc09-11ea-952b-ab274a0ae346.png">

... 0.4.1 is displayed.

**Comment by kevancress** [comment]
Should be fixed now in the release files and in master fa91f946110425f707c6b4804390b160b3cb6a0f

**Comment by globalcitizen** [comment]
Verified fixed. Thanks.
