### ISSUE TITLE
Error when trying to enable and wrong version shown - MeasureIt-ARCH-v0-4-5

### ISSUE THREAD

**Issue by r3sonant** [kevancress/MeasureIt-ARCH#104]
Hello.

I am receiving the error shown in the screenshot when trying to enable MeasureIt-ARCH-v0-4-5 on both Blender 2.83.2 and 2.83.3. The add-on also shows as version 0.4.1.

![Annotation 2020-07-23 071730](https://user-images.githubusercontent.com/11404006/88256987-9db0a300-ccb4-11ea-84f6-58e96498279a.png)

Thanks.

**Comment by kevancress** [comment]
Hey @r3sonant Thanks for the report! Merging this with https://github.com/kevancress/MeasureIt-ARCH/issues/105 since it's the same issue causing the enable failure
