### ISSUE TITLE
0.4.5: Dimension auto-flip imperfect

### ISSUE THREAD

**Issue by globalcitizen** [kevancress/MeasureIt-ARCH#107]
First of all, great job overall on the recent updates! In general the dimensions are far more legible now.

However, moving close to an axis appears to flip the dimensions.

Higher up position...

<img width="515" alt="Screen Shot 2020-07-25 at 12 16 56" src="https://user-images.githubusercontent.com/505366/88446860-ed3bce00-ce70-11ea-82c0-673a6ddf768f.png">

Lower down position...

<img width="528" alt="Screen Shot 2020-07-25 at 12 17 00" src="https://user-images.githubusercontent.com/505366/88446864-f167eb80-ce70-11ea-9416-92930eeaae4c.png">

As this flip does not appear to be useful, I wonder if there is a means to rectify it.

**Comment by kevancress** [comment]
Ahh Looks like I need to fine tune my text flipping thresholds! I'll try and take a look at this today, doing quite a bit of refactoring there  to set up for more direct control of text placement and to make it easier to add in scale based text sizing soon so I'll try and make sure this gets fixed too

**Comment by kevancress** [comment]
Should be fixed in 9ebcdeb701e43867beb72c53a0aa4daf7d7483b6

**Comment by globalcitizen** [comment]
Sorry for the dumb question but how do I get that latest version installed to test with?

I tried checking out your repo with git then zipping similarly structured to the released zipfile (ie. in a MeasureIt_ARCH subdir) but going through the install button yields an error as follows.

<img width="665" alt="Screen Shot 2020-07-29 at 09 27 02" src="https://user-images.githubusercontent.com/505366/88739385-c1c12800-d17d-11ea-880b-b795d77abe27.png">

I am happy to do a symlink or something from the installed version but wonder what is best practice here. I cannot find any clear Blender-world reference on how to keep your blender module that is checked out from git at the bleeding edge.

Might be worth considering adding this to the docs, also, since releases seem sporadic.

**Comment by globalcitizen** [comment]
Should I add the above as a separate issue?

**Comment by globalcitizen** [comment]
Added to [general suggestions issue](https://github.com/kevancress/MeasureIt-ARCH/issues/4).
