### ISSUE TITLE
Angle glitch (DIM PLACEMENT REFACTOR)

### ISSUE THREAD

**Issue by Sharkacuga** [kevancress/MeasureIt-ARCH#179]
is it suppose to do the weird angle?
![image](https://user-images.githubusercontent.com/57742974/125727353-9e779017-84f9-46ce-9d18-1763cf13f0b4.png)

**Comment by kevancress** [comment]
Hey @spyro12675 

Yeah there's some issues with the dimension placement system that can cause the text to get skewed like that.

A temporary  fix is to set the dimension view plane.

**Comment by kevancress** [comment]
Hey @spyro12675 

As far as I know, this is fixed in the latest development version of the addon. Please let me know if your still having any issues!
