### ISSUE TITLE
hatch only cross section

### ISSUE THREAD

**Issue by ekswathi** [kevancress/MeasureIt-ARCH#180]
Is there any way to hatch only the section area?

**Comment by kevancress** [comment]
Hey @ekswathi

This is my usual setup for hatching cut area's:

![boolean](https://user-images.githubusercontent.com/16860574/131376187-e059ef21-608b-481c-9d20-e66e42314e18.gif)

I use a cube as a boolean object with a "cut" material that has a hatch set up on it. Then on the object I want to section I add the 'cut' material to an extra material slot that isn't applied to any faces, and a Boolean modifier.

When the object is sectioned, the faces cut by the Boolean modifier get the 'cut' material assigned (and the hatch too).

**Comment by RadiumC** [comment]
Hello
When exporting as DXF, the lines are always yellow,continuous, and there are no hatches although its named after Line Style
Does it suppose to keep the line style from Measure Arch?
