### ISSUE TITLE
Attempting to drag measurement offset gizmo produces a Python AttributeError

### ISSUE THREAD

**Issue by DaneHoffman** [kevancress/MeasureIt-ARCH#181]
When clicking the "Show Gizmos" button in the MeasureIt_ARCH Show/Hide panel, there is a small arrow that appears perpendicular to the measurement. Presumably this controls the offset of a dimension measurement, but when I click and drag it, it produces a Python error that says: 

`File "C:\path\to\addon\measureit_arch_dimensions.py", line 1568, in invoke dimension = getattr(myobj, self.dimType)`

Operating system is Windows 10, Blender version is 2.92.0

**Comment by kevancress** [comment]
Hey @DaneHoffman are you using the latest development version from the main github page  there's some fixes to the gizmo system in there that might resolve this.

If its still an issue let me know!

**Comment by kevancress** [comment]
Hey @DaneHoffman 

Just confirmed that this is working as expected in the latest development version.

![gizmos](https://user-images.githubusercontent.com/16860574/131374889-51205d35-06b9-4be3-8550-691a782085bf.gif)

Closing this for now but let me know if you find any other issues!
