### ISSUE TITLE
how does the "Aligned" button work 

### ISSUE THREAD

**Issue by rulon** [kevancress/MeasureIt-ARCH#182]
I tried to measure between 2 objects (cubes).
The tool shows a strange result.
What distance does it show here? 
Thanks.

![blender-measure](https://user-images.githubusercontent.com/499425/131244056-8ad52f0d-ee69-4619-ab80-e3591eda5e53.gif)

**Comment by kevancress** [comment]
Hey @rulon 

Yep that's definitely a bug. The aligned dimension in that case should show the straight line distance between the two object origins.

Try using the latest development version (if you're not already) that might fix it. You can download it from the main github page.

If it's  still a problem I'll take a look and see if I can reproduce and fix the issue tonight.

**Comment by kevancress** [comment]
Hey @rulon 

Just confirmed that this is fixed and behaving as expected in the latest development version.

![fdasfdaws](https://user-images.githubusercontent.com/16860574/131372745-787e4f80-c879-4164-ad5c-f303cf1c628a.gif)

Closing this for now, but let me know if you run into any other issues!
