### ISSUE TITLE
Arrow style; length vs width ratio

### ISSUE THREAD

**Issue by marcusulpius** [kevancress/MeasureIt-ARCH#19]
Awesome tool!

Is there a way to change the arrow head style on the dimensions lines so they are longer, more streamlined?

Traditionally CAD arrows are longer and wider than the addon exhibits? Arrowheads more typically have  a 3:1 ratio in length vs width. In essence, what I am looking for is more akin to the "closed filled" arrowhead from AutoCAD. Currently, the arrow is too fat.

Love to ideas on how.

**Comment by kevancress** [comment]
Hey Marcus,

Thanks for the suggestion! I'v added an Arrow Angle property to the dimensions that lets you adjust the arrows shape. Let me know if that lets you get the look your going for!

![arrow angle](https://user-images.githubusercontent.com/16860574/62595551-c9bcf380-b8ac-11e9-88ea-3b352f46338f.gif)

**Comment by marcusulpius** [comment]
Wow, thanks!!!

**Comment by kevancress** [comment]
Great! If you download the latest master it should be in there now

**Comment by marcusulpius** [comment]
Thank you so much!!!
