### ISSUE TITLE
Axis Dimensions doesn't get the Offset value from Dimension Style settings.

### ISSUE THREAD

**Issue by raytry** [kevancress/MeasureIt-ARCH#190]
All other Axis Dimension Style settings seems to work properly except the Offset value (marked with red x). It remains at the default 50mm value.
Aligned Dimensions gets the Offset value properly (marked with green checkmarks).

![Screenshot_2021-09-29_11-25-21_edited](https://user-images.githubusercontent.com/9461704/135245212-6f5d284d-6e5f-473f-8452-858a9313abc0.png)

**Comment by kevancress** [comment]
Hey @raytry

Sorry for being so slow responding to this. Not sure when but this does seem to be fixed and working as expected in the latest development version of the addon. Let me know if your still having issues!
