### ISSUE TITLE
error message when deleting any object from the viewport

### ISSUE THREAD

**Issue by mizo1900** [kevancress/MeasureIt-ARCH#198]
![Screen-2021-11-23_19-10-56](https://user-images.githubusercontent.com/91334763/143071523-b2dc9369-dd2c-4498-b364-757a328575cc.jpg)
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MeasureIt_ARCH\measureit_arch_main.py", line 306, in draw
    col = layout.column(align=True, heading='Settings')
TypeError: UILayout.column(): takes at most 1 arguments, got 2

location: <unknown location>:-1

when the object is deleted from the outliner the error message doesn't appear
only appears when the object  is deleted directly from the viewport

**Comment by RadiumC** [comment]
I confirm the same issue

**Comment by kevancress** [comment]
@mizo1900 @RadiumC  

I haven't been able to reproduce this error in the latest development version.

could you post more detailed steps, or a demo file?

**Comment by kevancress** [comment]
Closing for now, let me know if this is still an issue!
