### ISSUE TITLE
angle measurement

### ISSUE THREAD

**Issue by rulon** [kevancress/MeasureIt-ARCH#199]
blender 2.93.3, 3.0
this addon 0.5.0
problem: does not show the angle dimension.
and visibility  somehow affects to other items:
![blender-angle](https://user-images.githubusercontent.com/499425/145821660-c246092a-afc7-45a8-b5b8-33cf6a25e1e8.gif)

**Comment by kevancress** [comment]
@rulon 

Sorry for the slow reply.

This seems to be fixed in the latest development version when using Blender 3.1 Stable
