### ISSUE TITLE
MeasureIt-ARCH fails when trying to enable in Prefs.

### ISSUE THREAD

**Issue by garyhaus** [kevancress/MeasureIt-ARCH#2]
![Screen Shot 2019-03-25 at 5 19 02 PM](https://user-images.githubusercontent.com/2287376/54954872-1fa68580-4f22-11e9-99e1-43c24c1d491c.png)

**Comment by kevancress** [comment]
Hey Gary, Thanks for the error report. Just made some changes that should fix it.

Try removing the old version in the preferences and installing this one: [MeasureIt-ARCH-master.zip](https://github.com/kevancress/MeasureIt-ARCH/files/3005589/MeasureIt-ARCH-master.zip)

Let me know how it goes!

**Comment by garyhaus** [comment]
FLAWLESS now!  Working sir thanks!

**Comment by kevancress** [comment]
That's great! Thanks for testing! Let me know if anything else comes up!

**Comment by garyhaus** [comment]
![Screen Shot 2019-03-25 at 5 45 17 PM](https://user-images.githubusercontent.com/2287376/54956209-cf312700-4f25-11e9-91ec-e6cb518d49ed.png)
looks fine in edit mode

**Comment by garyhaus** [comment]
![Screen Shot 2019-03-25 at 5 45 24 PM](https://user-images.githubusercontent.com/2287376/54956223-da845280-4f25-11e9-82b2-df832a4acdb7.png)
broken in object mode?  or is this intended?

**Comment by kevancress** [comment]
Intended but I could probably communicate why better. 

In edit mode the annotation gets anchored to the selected vertex, in object mode it gets anchored to the objects origin, I should probably point that out in the tool tip or give a popup warning

**Comment by garyhaus** [comment]
ok thanks for the response

**Comment by kevancress** [comment]
No problem! Feedback like that really helps me try and make things more intuitive for the next release.
