### ISSUE TITLE
Error when trying to use Measure it Arch Render - If View Output Path does Not Exist, or does not have write permissions

### ISSUE THREAD

**Issue by RadiumC** [kevancress/MeasureIt-ARCH#209]
I cannot render with the Measure It Arch render feature
When tring any of the three buttons, it throws error 
PermissionError:[Win Error5] Access is denied `Renders
![render_error](https://user-images.githubusercontent.com/13616757/162606712-76c1a835-8634-4118-b994-c5585bceef7f.jpg)
`

**Comment by kevancress** [comment]
Hey @RadiumC

This Error occurs when the output path defined in the active view either doesn't exist, or is a folder you don't have permission to access.

![image](https://user-images.githubusercontent.com/16860574/163034495-023dece6-1b73-4b68-9a15-006b7c98281d.png)


I should add a more descriptive error message, and set up the addon to automatically create the output folder if the one specified doesn't exist yet

**Comment by RadiumC** [comment]
Thanks, it works now
How do I make it work with Blender Bim? Do i just need to change the name of the folder?
Where do I get the latest git branch?

**Comment by RadiumC** [comment]
I think the description is incomplete in the Readme file?

Latest git master
[Install Blender 2.8 or higher](https://www.blender.org/download/)
Locate your platform and Blender installation specific Blender addons directory:
On Windows, this is usually /Program Files/Blender Foundation/Blender BLENDER_VERSION/BLENDER_VERSION/scripts/addons
On Mac, this is usually /Applications/Blender.app/Contents/Resources/BLENDER_VERSION/scripts/addons

**Comment by kevancress** [comment]
@RadiumC 

Sorry yeah the docs are a bit out of date.

Changing the output path to an existing folder should work, and renders should automatically be saved there after you hit the render button.

to get the latest version of the addon go to the main git page, and go to the "development" branch. Download that and extract the addon into the Blender Addons Directory (the paths you mentioned above) and then it should work. You can also use the install button from the Blender Addons Menu.

I'd recommend using the Addon with Blender 3.1 Stable. That's what I'm working in these days, so it's most stable there.

I haven't done much work using both MeasureIt_ARCH and Blender BIM. We did some integration tests about a year ago, but I haven't had time to keep up with the Blender BIM team (but they're doing amazing stuff!). Most of my work is single family residential too, so I'm generally not needing a full BIM workflow in my day-to-day.

**Comment by RadiumC** [comment]
Thanks for replying!
I am also not too heavy on production grade CAD, in fact I do concept design most of the times and recently dived into Blender but i miss the CAD representation and creation capabilities of Bim programs. Actually right now i  think your plugin is even better for what i am looking for. I would like to be able to work in floorplan views and generate plans, sections, etc to share but also to understand my design. Sorry for going too long on here.  
I noticed you have a nice template with CAD views. Can you also generate hatches or you use it in conjunction with boolean tools or BlenderBim section cuts?

I think i have the development branch because the folder is named  MeasureIt_ARCH-development
Do i need to rename it and change the dash "-" into underscore "_" to get recognized by Blender Bim? 
I was hoping that BlenderBim would export MeasureIt Arch dimensioning too.
Using 3.1 Stable here too as well.

**Comment by kevancress** [comment]
Hey @Radium 

Yeah my approach to plans and sections is generally to have all the 3D elements in my scene set up with a Boolean difference modifier all using a single large cube as the cutting object. Objects cut with a Boolean modifier will actually take on the material of the cutting object, as long as the source object has a material slot with the cut material available, which is how I do a simple hatch on cut faces. Then I just set up my views on different frames, and move and keyframe the cutting object depending on if its a plan, section etc. 

Kinda hard to describe but here's a video showing my usual set up on a demo project:


https://user-images.githubusercontent.com/16860574/163683707-2ce216d6-51dd-4c7e-a8f8-b72c0f434c1a.mp4



I usually add a bit of detailing just in 2D for each particular view as well, makes it pretty quick to pull together concept plans:

![_PLAN_0001](https://user-images.githubusercontent.com/16860574/163683607-f4e11af7-da2b-4c0f-9676-81ecf3c87f0d.svg)

**Comment by kevancress** [comment]
I'll have to look into the BlenderBIM integration stuff later when I get some more time. It's been a while since I've looked at that code and what it takes to get them working together

**Comment by RadiumC** [comment]
Thank you for the tips and the video !
Did you import the symbols for doors/windows from standard DWG libraries?
By the way, is the Hatch feature in Material Properties, part of your addon or is it in the standard Blender? Or is it from Blender Bim? I only recently noticed it and its really powerfull!

**Comment by kevancress** [comment]
@RadiumC No problem!

For 2D symbols I either make them in Blender, or use the built in .dxf importer to bring in blocks exported from a .dwg

The hatch feature panel in the material properties is from MeasureIt_ARCH yeah, I think blenderBIM has a way of doing hatches too though.

**Comment by RadiumC** [comment]
@kevancress Awesome feature! How do I use the Pattern setting for the Hatch? I see there is a collection picker but  what does it need to have for a pattern?

**Comment by kevancress** [comment]
@RadiumC  If you've got a collection selected then the hatch will draw all the edges in that collection as the hatch pattern.

It tiles based on the 0m-1m square in the xy plane. So I usually set up a separate scene and make my hatch collections there:

![image](https://user-images.githubusercontent.com/16860574/164033710-aaef498e-aa6b-4bee-8921-724f7ee1fd51.png)

**Comment by RadiumC** [comment]
Hmm i wasn`t able to generate any hatch. Maybe there was something with the thickness or something else.  I did create a series of edges at  world center from 0 to 1m.
Do you mind if you can show an example of setting up a hatch?
