### ISSUE TITLE
Area not centered

### ISSUE THREAD

**Issue by giudansky** [kevancress/MeasureIt-ARCH#218]
Not a huge issue but its annoying. I cant get surface area measure right to the center of a face. Tried many workarounds but just cant do it. Is it a bug or what am I doing wrong ?

See attach below:
https://i.imgur.com/vObSSUp.jpg

Thanks

**Comment by kevancress** [comment]
Hey @giudansky

sorry for the slow response. this should be fixed in the latest development version of the addon.

if you still have issues with area text placement please re-open this issue and let me know
