### ISSUE TITLE
More Area text placement oddness

### ISSUE THREAD

**Issue by baldyman01** [kevancress/MeasureIt-ARCH#225]
Blender 3.2.1 , MeasureIT_ARCH development 12/7/22

If I start a new file and add an area to the top face of the default cube the text comes out in the X-Y plane.
If I add a new cube and add an area to the top of that it comes out in the Y-Z plane and I can't find a way to change it. The view plane override was what I assumed should control that but it appears to change nothing.

![Screenshot from 2022-07-13 15-33-13](https://user-images.githubusercontent.com/33987743/178760466-3f9e33bd-b36c-41aa-a35c-c6ab3edc4325.png)
[MeasureIT_ARCH Area Text Plane.blend.zip](https://github.com/kevancress/MeasureIt_ARCH/files/9103272/MeasureIT_ARCH.Area.Text.Plane.blend.zip)

**Comment by kevancress** [comment]
Hey @baldyman01

Sorry for the slow reply. I started working on a fix for this in 1cf1c51abb03f1669fdee82f1b538f3493c0820a so if you grab the latest development version it should be slightly better.

Still some remaining weirdness with area dimension though... gonna take a better look at their draw code this weekend and try and get them tunned up

**Comment by baldyman01** [comment]
Nice job - Areas are now centred and are aligned correctly even on complex objects like icospheres. Offset scales correctly with the object as well.
