### ISSUE TITLE
Feature Request - Embed Grease Pencil SVG

### ISSUE THREAD

**Issue by baldyman01** [kevancress/MeasureIt-ARCH#228]
So I've been tinkering with Grease Pencil as a replacement for Freestyle for rendering plans and it seems to be much more controllable than Freestyle and is working well.

I'd be interested to know if embedding a Grease Pencil SVG render might be possible.

**Comment by baldyman01** [comment]
Ignore me, I'm a dipshit.

**Comment by kevancress** [comment]
@baldyman01 No Worries! Honestly issue reports like this are helpful too because they remind me that I actually need to update the documentation for this addon too!!

Gonna take a crack at updating the docs this weekend!
