### ISSUE TITLE
Line Group Cache Issue, Deleted Line Groups Re-appear if new line group with same name is used.

### ISSUE THREAD

**Issue by ccalvoga** [kevancress/MeasureIt-ARCH#231]
Thanks for this increadible addon.
I realize that when you delete a Line Group the block of data is keeped. If you create a Line Group then you delete it, create a new one completely different to the previous one and change the name of this one to the deleted one, the new Line Group is the same as the deleted one.

**Comment by kevancress** [comment]
Hey @ccalvoga

What version of the addon are you using? I think I fixed this already, so if you download and install the development version from the main github page that should fix this.

in either case, this is an issue with how line groups are cached for drawing on the gpu, tabbing into and out of edit mode on the object should fix it too

**Comment by ccalvoga** [comment]
Hi @kevancress ,
I'm working with version 0.4.7. 
I have  tabbed into and out of edit mode on the object and still re-appear.
Here, there is video.

https://user-images.githubusercontent.com/40768363/185577240-553d42a3-76e5-4056-99cd-60ea1771776d.mp4

**Comment by ccalvoga** [comment]
Hi Kevan,
I have dowloaded last release and it work perfect.
Thanks

**Comment by kevancress** [comment]
Great thanks!

Let me know if  you find any other issues
