### ISSUE TITLE
Add Operator to Duplicate Styles

### ISSUE THREAD

**Issue by ccalvoga** [kevancress/MeasureIt-ARCH#244]
Hi Kevan,
It would be nice to add a bottom for copy parameter from a style to a new style. Same for Views. 
have a nice day,
Carlos

**Comment by kevancress** [comment]
Hey @ccalvoga 

This actually already exists for views, its under the extras menu next to the list:

![Screenshot (1)](https://user-images.githubusercontent.com/16860574/191882881-987858a9-f509-4e41-b4c2-c5d5aa871cbd.png)

But your right I should definitely add this for styles as well!

**Comment by kevancress** [comment]
Hey @ccalvoga

Just added a duplicate styles operator, its in the extras menu for styles


![ui-styles-extras](https://user-images.githubusercontent.com/16860574/193422685-a11904ed-3aa5-4571-9877-3a1719b8a5fe.JPG)

Closing this for now, let me know if there's any problems!

ca0d6a3fe4779b72c1ae585a7d62eec409fa07d3

**Comment by ccalvoga** [comment]
Hi @kevancress ,
thanks a lot, 
It is really usfull when you have a lot of styles assinged to different views.

Carlos
