### ISSUE TITLE
Is it possible to export the link map of vertices rendered in freetyle?

### ISSUE THREAD

**Issue by lisiyao21** [kevancress/MeasureIt-ARCH#245]
It is an amazing work!!!

I am a beginer user of blender and it is a black box to me. If I understand correctly, the freestyle is going to select suggestive edges from the whole view map (the mesh) and draw these edges to color. Is it possible to export/record those rendered edges/vertex info (including id, 2d position, 3d position...) for further processing?

Thank you!!

**Comment by kevancress** [comment]
Hey @lisiyao21

This is probably a better question for the freestyle developers. MeasureIt_Arch can embed freestyle linework in its outputs but other than that it doesn't interact with freestyles view map data at all, so I'm not sure what data is available for export from freestyle.

**Comment by lisiyao21** [comment]
Thank you for your kind reply!!!

**Comment by lisiyao21** [comment]
So sorry for my late response due to hanging out...  Since I'm really new to blender, could you guide me which specific person should I consult? Thank you so much!!

**Comment by kevancress** [comment]
@lisiyao21

hmm well the main page for freestyle is here https://freestyle.sourceforge.net/index.php and it has a lot of data about how the system works... but also hasn't been updated in several years, and I don't think any of the contact info is up to date...

I think the [Blender NPR](https://blendernpr.org/) team did some work on the Freestyle UI a little while ago, so they might be able to help, they've got a pretty active twitter account that should work to get in contact with them.

For other line drawing methods I know [Yiming Wu](https://twitter.com/ChengduLittleA) has been developing the [Grease Pencil Line Art Modifier](https://docs.blender.org/manual/en/latest/grease_pencil/modifiers/generate/line_art.html) which could be helpful.

Also MeasureIt_ARCH does have its own Line Group system for drawing lines, but its mainly set up for technical drafting, and doesn't do things like suggestive contour edges like freestyle or the line art modifier would.

Hope that helps!!!
