### ISSUE TITLE
RASTER RENDER IS BROKEN (Blender 3.4+)

### ISSUE THREAD

**Issue by kevancress** [kevancress/MeasureIt-ARCH#253]
Raster rendering is not working, for some reason it's just drawing the screen texture...

**Comment by kevancress** [comment]
Looks like this has to do with changes to the gpu module in 3.4 + and not somthing I broke when messing with the draw pipeline... yay

**Comment by vollstock** [comment]
On the mac, ist’s not only not rendering. The addon fails completely (won't even install).
Let me know, whether this is different on your machine and you want me to provide some Mac-specific info.

**Comment by kevancress** [comment]
Hey @vollstock This is likely a separate problem from the GPU draw issues, so I've opened a separate thread for it: https://github.com/kevancress/MeasureIt_ARCH/issues/254 

It enables okay on windows so if you could let me know your Blender version, what version of the addon you downloaded, version of macOS, and any error messages that pop up when you try to enable the addon that would be great! Hopefully I can get that fixed today

**Comment by kevancress** [comment]
Looks like the raster draw issue was just an issue reading frambuffers on the particular Blender 3.4 Alpha version I was using. 3.3, 3.41 stable, and 3.5 alpha don't have this issue. Closing for now
