### ISSUE TITLE
Default text preview is very low res

### ISSUE THREAD

**Issue by drewp** [kevancress/MeasureIt-ARCH#259]
![image](https://user-images.githubusercontent.com/104003/215245490-6f60fe67-2967-41b4-9626-98ad1f14e251.png)

My scene units are cm, and I don't think my scene is excessively large or small. 

blender 3.5 alpha from 2023-01-17

**Comment by drewp** [comment]
Aha, I found the scene settings area, which is apparently like this by default: 
![image](https://user-images.githubusercontent.com/104003/215293164-54580a7d-7179-4caf-983b-bf038a58ddfe.png)

These let me dial to an acceptable res, though it would obviously be nice if the addon could come up with something more sensible in my case.

**Comment by kevancress** [comment]
Hey @drewp

Yeah I've been trying to come up with a better balance for Text resolution! The main problem really is that the addons performs pretty slowly when drawing lots of medium-high resolution text, which isn't so bad at render time, but makes the viewport really sluggish (hence the lower default / preview resolution in the viewport). 

I might dial it up to 150 ppi by default, which looks a little cleaner, and doesn't hurt viewport performance too much... but ultimately I need to work on the text drawing performance to properly resolve this.

**Comment by kevancress** [comment]
Default is now 150ppi, text drawing performance is a little better after aff07ffe609829eac5c41caf8e1392b44f000a32

closing for now
