### ISSUE TITLE
I cant find hide units Or I wish Units as NONE would have precision 

### ISSUE THREAD

**Issue by Blendersbrontobyte** [kevancress/MeasureIt-ARCH#265]
Ether way I hope "hide units" in in settings settings  does not disappear.  And I hope to see units set as NONE have precision.  Ethier one of those would be great.   
 Thank you

**Comment by kevancress** [comment]
Hey @Blendersbrontobyte

Hide units is still available under the scene settings 
![image](https://github.com/kevancress/MeasureIt_ARCH/assets/16860574/bdcb7859-5bc2-4a3c-ab95-96b48e8a0e55)

No plans to remove this

**Comment by Blendersbrontobyte** [comment]
Keven,
Thank you – your program opens doors for a lot of people. thank you for your reply.
Don Matteson
Cody Wyoming
