### ISSUE TITLE
Can MeasureIt display a furniture design's bounding box dimensions?

### ISSUE THREAD

**Issue by redfrog682** [kevancress/MeasureIt-ARCH#27]
I import wrl files of furniture designs to Blender.  These designs have many different parts.  I would like to display overall dimensions like shown in the photo below:

![overall_dimensions](https://user-images.githubusercontent.com/59268068/71493972-8251e800-27f8-11ea-9494-476267369b5c.jpg)

I have tried to join all the parts, get a bounding box for the overall furniture design, then enable "Edge Length" in Viewport overlays, but all the individual parts' dimensions get displayed.  I end up with a mess like this:

![edge_length](https://user-images.githubusercontent.com/59268068/71494078-1de35880-27f9-11ea-8081-ae5e57e179e1.jpg)

It seems all parts' dimensions are shown except for the overall bounding box's dimensions, which are what I need.

Can MeasureIt display bounding box dimensions?  That seems to be the most accurate way to display overall dimensions.  Thank you!

**Comment by kevancress** [comment]
Hey @redfrog682 

Thanks for the suggestion! I've just started implementing bounding box dimensions. They're still a bit rough right now, the orientation isn't always the best, but it's a start. They're in the master branch now if you want to test them out! I'll be improving them over the new few weeks too I hope.

Cheers!

**Comment by kevancress** [comment]
Here's a quick demo too.

![bbdims](https://user-images.githubusercontent.com/16860574/73596242-a3d87a80-44ee-11ea-8180-52c787b80925.gif)

**Comment by kevancress** [comment]
Implementation started in 1c15ac486471910d4dab00932e70998fa7249580

See https://github.com/kevancress/MeasureIt-ARCH/issues/35 for future development and discussion
