### ISSUE TITLE
Axis Aligned Dimensions not using Object Matrix

### ISSUE THREAD

**Issue by kevancress** [kevancress/MeasureIt-ARCH#284]
> [20240822_10h56m46s_grim](https://github.com/user-attachments/assets/2280d60f-2995-43e7-8463-b76eeeb0ef74)
> Any idea why the dimensions for axis specific selections draws them offset from the vertices? It appears to use the origin of the world instead of the objects median.
> 
> Looking for a way to bypass this. Otherwise I will just photo edit the results for what I need.

_Originally posted by @Myrkskog in https://github.com/kevancress/MeasureIt_ARCH/issues/283#issuecomment-2304894491_

**Comment by kevancress** [comment]
Fixed in 44ff6103564ab9534b91d258daa261169c36bb5e I think.

@Myrkskog can you give the latest version a test and let me know if this fixes the issue for you?

Thanks!

**Comment by Myrkskog** [comment]
Yes it works now! Thank you for the quick fix.
I am using Blender 4.2.1 Hash 396f546c9d82
