### ISSUE TITLE
"Annotations" missing

### ISSUE THREAD

**Issue by Blenderbugg** [kevancress/MeasureIt-ARCH#3]
Hi,
"Annotations" menu item not appearing under "Custom Properties"

<img width="379" alt="Screen Shot 2019-03-26 at 10 52 53 am" src="https://user-images.githubusercontent.com/28837471/54961790-35fe2100-4fb6-11e9-9731-c30b6bfb0faf.png">

**Comment by kevancress** [comment]
Hey Blenderbugg,

Right now the menu panels don't show up unless the active object already has an annotation added to it, same with the dimension and line menu panels.

If its still not showing up after an annotation has been added let me know.

![annotations panel](https://user-images.githubusercontent.com/16860574/54963702-0d3b4480-4f40-11e9-9a90-93e1a8139217.gif)

**Comment by Blenderbugg** [comment]
Ah yes... got it. Is there a way to have it on by default? AT least you would know its there to use. Anyway, I am making a little list of suggestions and observations as I go - Where should I post them?

Eric

**Comment by kevancress** [comment]
Was hoping to try and reduce UI clutter by hiding them when they're not used, but your right having it be more discover-able would be really valuable! 

In the next couple weeks I'm hoping to rework the settings UI into something similar to [This Modifiers UI Concept](https://twitter.com/FinEskimo/status/1107053329312608257) It's not too cluttered and fits well with the rest of blenders UI system I think?

Thanks so much for putting together a list of suggestions!! I think right now the Issue tracker is the best place to have discussions on these things that keeps them tied to the project and easy to keep track of, maybe I'll start a Features and Suggestions thread to keep everything collected, and I can break out individual projects from there?
