### ISSUE TITLE
Rendering MeasureIt Arch fails if output was once set to .png but has changed to a different format

### ISSUE THREAD

**Issue by MarcelQ** [kevancress/MeasureIt-ARCH#44]
Alright so if you set the output type to .png and render the Measureit Arch annotations all works fine. However if you change the output to anything other than png, lets say .jpg, measureit_arch_render.py will log 2 errors and fail to render. So Its seem like the addon its storing some of the render settings and not accounting for the changes made to updated render output settings as I can see one of the errors has to do with the color_depth values stored for the .png image format that was set before (This is just my initial observations without looking at whats happening in the code). I have not tried to see if the render will fail if other combinations output formats are selected or if this is only related to the .png format. 

To get the render to work again one would need to change the output format back to .png, otherwise rendering in other formats will continue to fail.

Here is the error from the console: 

```
Traceback (most recent call last):
  File "C:\Users\MarcelQ\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MeasureIt-ARCH-master\measureit_arch_render.py", line 120, in execute
    if render_main(self, context) is True:
  File "C:\Users\MarcelQ\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MeasureIt-ARCH-master\measureit_arch_render.py", line 233, in render_main
    settings.color_depth = '16'
TypeError: bpy_struct: item.attr = val: enum "16" not found in ('8')

location: <unknown location>:-1
```

**Comment by kevancress** [comment]
Hey Marcel! Thanks for the issue report.

MeasureIt-ARCH always saves to a 16 bit RGBA .png and it looks like it was trying to overwrite the users render settings with that colour depth. Just pushed a commit that should fix it to master!

Cheers,
Kevan
