### ISSUE TITLE
Unclear what license

### ISSUE THREAD

**Issue by Moult** [kevancress/MeasureIt-ARCH#50]
Would it be possible to add a license file to this repo so we know what license it is under? I'm adding your project to https://wiki.osarch.org/index.php?title=AEC_Free_Software_directory

Cheers :)

**Comment by kevancress** [comment]
Hey Dion!

Thanks for the Heads up, MeasureIt-ARCH is GPL 3.0. I've just added a license file in 0cfe46cedcab22298ad0713096eebb82b7541b6a

The AEC Free Software Directory looks like an amazing resource!! Thanks so much for putting it together, and for including MeasureIt-ARCH!

Cheers!

**Comment by Moult** [comment]
Thanks! Added the license to the wiki! Glad you enjoyed it :) Please feel free to spread the word.
