### ISSUE TITLE
better bounds dimensions

### ISSUE THREAD

**Issue by meutzitzu** [kevancress/MeasureIt-ARCH#69]
Bounds dimensions are awesome ! For the type of stuff I'm doing they have the potential to really really save me some time, but I've noticed the "smart align" feature, that flips the dimensions 90 degrees depending on the view angle to avoid highly skewed projections is kinda working but I've noticed it doesn't actually change the edge the dimension refferences. I think it just starts with the 3 edges that look best when you add the dimension, and then tries to flip them as best it can so they are always as perpendicular to the view direction as possible. However, it would be much better if it also chose between the 4 edges of the bound box for each dimension whichever is the farthest (and is still visible ) so as to avoid drawing the bound dimension over the object

**Comment by kevancress** [comment]
Totally Agree! and a placement system like this is in the works, Gonna merge this with https://github.com/kevancress/MeasureIt-ARCH/issues/63 to keep things together
