### ISSUE TITLE
Default 45 degree offset for vertices is inconvenient

### ISSUE THREAD

**Issue by globalcitizen** [kevancress/MeasureIt-ARCH#77]
The default of a 45 degree offset for a dimension of two vertices on a single plane is inconvenient for both plans and elevations, which by far represent the most popular output types.

![45-degree-offsets](https://user-images.githubusercontent.com/505366/83483982-3877d700-a4e7-11ea-88d3-32b2b97d1220.jpg)

Unsure of this is fixed in the planned v0.4 release as I am unable to get the direct from source version working (tried zipping the Github repo, for some reason Blender wouldn't recognize it).

**Comment by kevancress** [comment]
@globalcitizen  Yep this default behavior has been changed in v0.4 + to automatically align with a plan or elevation view depending on the users viewpoint

hmm... strange that the zipped repo isn't being recognized... I just put up a release for version 0.4 so hopefully that installs correctly, let me know!

If your interested in keeping up to date with the latest master and reloading the add-on directly from the cloned repo I've been using Jacques Lucke's visual studio code extension for Blender addon development, it's worth checking out: https://marketplace.visualstudio.com/items?itemName=JacquesLucke.blender-development

**Comment by globalcitizen** [comment]
Tried to install v0.4 beta source code zip file `MeasureIt-ARCH-mARCHv0.4.zip` and got this error.

<img width="658" alt="Screen Shot 2020-06-03 at 21 11 14" src="https://user-images.githubusercontent.com/505366/83630297-edd98600-a5de-11ea-9ea4-1d85d894e1e4.png">
