### ISSUE TITLE
Local coordinates for axial dimensions 

### ISSUE THREAD

**Issue by meutzitzu** [kevancress/MeasureIt-ARCH#81]
I want to be able to rotate dimensioned object and keep the dimensions as they are ( relative to it ), so a helpful feature would be to use the object's coordinate system as the refference for the dimensions

**Comment by kevancress** [comment]
Hey @meutzitzu, great suggestion!

I've added an option to use the local space the x,y or z axis of any object as the measurement axis for axial dimensions through the 'Custom Axis Object" property. It's in the latest master now so check it out and let me know what ya think!

![Arbitrary Axis Dims](https://user-images.githubusercontent.com/16860574/83676419-a20bea00-a5a8-11ea-9b31-314a19320495.gif)
