### ISSUE TITLE
v0.4 beta: Zipfile installs but addon does not activate

### ISSUE THREAD

**Issue by globalcitizen** [kevancress/MeasureIt-ARCH#82]
Tried to install v0.4 beta source code zip file `MeasureIt-ARCH-mARCHv0.4.zip`. Install worked fine, the module appeared in the available modules list. However, when I enable it by clicking the checkbox I get this error:

<img width="658" alt="Screen Shot 2020-06-03 at 21 11 14" src="https://user-images.githubusercontent.com/505366/83630297-edd98600-a5de-11ea-9ea4-1d85d894e1e4.png">

**Comment by kevancress** [comment]
ah sorry that's a naming error, the folder inside the .zip shouldn't have had a "." in the name. I've updated the zip file on the release page.

If you remove the version that you have installed, restart blender, and then install the new .zip package from the [release page](https://github.com/kevancress/MeasureIt-ARCH/releases/tag/mARCHv0.4) called "MeasureIt-ARCH_v04.zip" it should work fine.

**Comment by globalcitizen** [comment]
Resolved.
