### ISSUE TITLE
Side of measure not consistent ?

### ISSUE THREAD

**Issue by s-leger** [kevancress/MeasureIt-ARCH#88]
When i do setup multiple measure using a list of vertex coordinates, the side of measure with respect to segment may change. Can't figure what's the logic behind coordinate side. Any insight ?
 
```
 |______|        
 |      |
 x      x      x  
        |______| 
        |      |

```

**Comment by kevancress** [comment]
Hey Stephen, I cant seem to reproduce this, could you record a .gif and post it so I can see?

The position of the measurement should always be consistent, its calculated at draw time using the select_normal( ) method in measureit_arch_geometry.py

the function uses the dimensions view plane, the objects geometry and the users view point to determine the placement direction vector for the dimension... but it should produce the same result for two pairs of co-linear points...

if the adjacent face normals are flipped, or if the dimension distance values are different then that could lead to this result also
